"use client";
import { brand } from "@coffee/brand";
import Link from "@/components/PreviewLink";
import { List, X, Bag } from "@phosphor-icons/react";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";

const links = [["/", "Home"], ["/menu", "Menu"], ["/story", "About us"], ["/stores", "Stores"]] as const;
export function SiteHeader({ orderUrl }: { orderUrl:string }) { const path=usePathname().replace(/^\/preview(?=\/|$)/,'')||'/'; const [open,setOpen]=useState(false); return <><header className={`site-header home-header${path === "/story" ? " about-overlay-header" : ""}`}><Link className="site-brand" href="/" onClick={()=>setOpen(false)}><img src={brand.logo} alt={brand.name}/><span><strong>{brand.name}</strong><small>{brand.tagline}</small></span></Link><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X size={24} aria-hidden/>:<List size={24} aria-hidden/>}</button><nav className={open?"open":""} aria-label="Primary navigation">{links.map(([href,label])=><Link key={href} aria-current={path===href?"page":undefined} className={path===href?"active":""} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}<a className="nav-order" href={orderUrl}><Bag size={18} aria-hidden/>Order pickup</a></nav></header>{open&&<button className="nav-backdrop" type="button" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}</> }
export function MotionInit(){const path=usePathname();useEffect(()=>{let observer:IntersectionObserver|undefined;const frame=requestAnimationFrame(()=>{const nodes=[...document.querySelectorAll<HTMLElement>("[data-reveal]")];if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){nodes.forEach(node=>node.dataset.visible="true");return}observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){(entry.target as HTMLElement).dataset.visible="true";observer?.unobserve(entry.target)}}),{threshold:.08,rootMargin:"0px 0px 4%"});nodes.forEach(node=>observer?.observe(node))});return()=>{cancelAnimationFrame(frame);observer?.disconnect()}},[path]);return null}
export function SiteFooter({orderUrl}:{orderUrl:string}){return <footer className="site-footer home-footer"><div><img src={brand.logo} alt=""/><div><strong>{brand.tagline}</strong><p>{brand.description}</p></div></div><nav>{links.slice(1).map(([href,label])=><Link key={href} href={href}>{label}</Link>)}<a href={orderUrl}>Order online</a></nav><small>© {new Date().getFullYear()} {brand.name}. {brand.photoNote}</small></footer>}
